/*
	IlegalesGeneral.lua, en este archivo se definen los NPCs ilegales generales.
	Estos NPCs pueden ofrecer diferentes servicios ilegales, como la venta de ganzúas para vehículos.
	El archivo contiene una tabla que define las propiedades y comportamientos de cada NPC ilegal.
*/

return {
	{ 	-- INTERCAMBIO DE GANZUAS NORMALES A GANZUAS PARA VEHICULOS (TABLET BOOSTING) 
		blip = false,
		blipType = 442,
		blipText = 'Ganzuas 1',
		blipColor = 15,
		blipScale = 0.6,  
		npc ='csb_grove_str_dlr', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'M.K',                                                
		dialog = 'Venga, ¿qué quieres? O lo tomas o lo dejas.',                                                        
		coordinates = vector3(2892.21, 4371.81, 49.31),   
		heading =  228.44,                                             
		options = {                                                            
			{'<i class="fa-solid fa-gun"></i>Interactuar', 'Quest:Ganzuas', 'c'},
		},
	}, 

	{ 	-- INTERCAMBIO DE GANZUAS NORMALES A GANZUAS PARA VEHICULOS (TABLET BOOSTING) 
		blip = false,
		blipType = 442,
		blipText = 'Ganzuas 2',
		blipColor = 15,
		blipScale = 0.6,  
		npc ='csb_grove_str_dlr', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'P.B',                                                
		dialog = 'Venga, ¿qué quieres? O lo tomas o lo dejas.',                                                        
		coordinates = vector3(-3088.72, 652.84, 0.88),   
		heading = 138.49,                                             
		options = {                                                            
			{'<i class="fa-solid fa-gun"></i>Interactuar', 'Quest:Ganzuas', 'c'},
		},
	}, 

	{ -- IITEMS PARA COMPLETAR EL BOOSTING
		blip = false,
		blipType = 59,
		blipText = 'ItemsIlegales',
		blipColor = 15,
		blipScale = 0.6,
		npc ='a_f_y_skater_01',                                              
		uiText = 'Blade Roozsv',                                                        
		dialog = 'Artilugios raretes',                                                                
		coordinates = vector3(-1185.69, -1805.50, 2.91),
		heading = 181.26,                                                   
		options = {                                                            
			{'<i class="fa-solid fa-building-memo"></i>Interactuar', 'opensellMenu:gpshackingdevice', 'c'},
		},
	},

	{ -- COMPRAR TABLET BOOSTING
		blip = false,
		blipType = 59,
		blipText = 'ItemsIlegales',
		blipColor = 15,
		blipScale = 0.6,
		npc ='a_f_y_skater_01',                                              
		uiText = 'María Asunción',                                                        
		dialog = 'Artilugios raretes',                                                                
		coordinates = vector3(-177.08, -1012.05, 20.28),
		heading = 243.17,                                                   
		options = {                                                            
			{'<i class="fa-solid fa-building-memo"></i>Interactuar', 'opensellMenu:boosting', 'c'},
		},
	},

	{ -- COMPRA DE ITEMS PARA ROBOS: BOLSA, CUERDA, TALADRO, ORDENADOR ENCRIPTADO
		blip = false,
		blipType = 59,
		blipText = 'ItemsIlegales',
		blipColor = 15,
		blipScale = 0.6,
		npc ='a_f_y_skater_01',                                              
		uiText = 'Susi',                                                        
		dialog = 'Artilugios raretes',                                                                
		coordinates = vector3(1232.52, -1084.87, 37.53),
		heading = 123.19,                                                   
		options = {                                                            
			{'<i class="fa-solid fa-building-memo"></i>Interactuar', 'opensellMenu:robos', 'c'},
		},
	},

	{ -- COMPRA DE ITEMS PARA ROBOS: BOLSA, CUERDA, TALADRO, ORDENADOR ENCRIPTADO
		blip = false,
		blipType = 59,
		blipText = 'ItemsIlegales',
		blipColor = 15,
		blipScale = 0.6,
		npc ='a_f_y_skater_01',                                              
		uiText = 'Susi',                                                        
		dialog = 'Artilugios raretes',                                                                
		coordinates = vector3(657.45, -1046.19, 21.58),
		heading = 349.66,                                                   
		options = {                                                            
			{'<i class="fa-solid fa-building-memo"></i>Interactuar', 'opensellMenu:robos', 'c'},
		},
	},

	{ -- VENDER ANILLOS 
		blip = false,
		blipType = 442,
		blipText = 'Venta Joyeria',
		blipColor = 15,
		blipScale = 0.6,
		npc ='csb_grove_str_dlr', 
		uiText = 'Carita',                                                        
		dialog = 'Venta de joyas', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},                                                      
		coordinates = vector3(1045.31, -2510.04, 27.46),
		heading = 354.06,    
		options = {                                                            
			{'<i class="fa-solid fa-building-memo"></i>Interactuar', 'rDialog:sell:jewelry', 'c'},
		},                                     
	},

	{ -- PAWNSHOP VENDER; RELOJ DE ORO, RELOJ, CADENA DE PLATA, ANILLO DE ORO
		blip = true,
		blipType = 280,
		blipText = 'PawShop / compra y ventas',
		blipColor = 15,
		blipScale = 0.75,
		npc ='g_m_m_mexboss_01',                                                     
		anim = {                                                            
			animDictionary = 'abigail_mcs_1_concat-0',
			animationName = 'exportcamera-0', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Leo Scott',                                                        
		dialog = '¡Bienvenido a la PawnShop! ¿En qué le puedo ayudar?',                                                
		coordinates = vector3(-157.86, -1341.98, 29.03),  
		heading = 258.37,                                                  
		options = {                                                            
			{'<i class="fa-solid fa-seal-question"></i>¿Qué tienes para venderme?', 'newpawshop:pawnshop', 'c'},
			-- {'<i class="fa-solid fa-seal-exclamation"></i>¿Qué tienes para comprar?', 'newpawshop:openshop', 'c'},
		},
	}, 

	{ -- VENTA DE SPRAY Y DISOLVENTE 
		blip = false,
		blipType = 59,
		blipText = 'Pintura y disolvente para yonkis',
		blipColor = 15,
		blipScale = 0.6,
		npc ='a_m_y_hasjew_01',                                              
		uiText = 'Thiago',                                                        
		dialog = 'Pintura y disolvente para yonkis',                                                                
		coordinates = vector3(2200.60, 5198.87, 60.12),
		heading = 154.66,                                                   
		options = {                                                            
			{'<i class="fa-solid fa-building-memo"></i>Interactuar', 'opensellMenu:ilegalesspray', 'c'},
		},
	},

	{ -- VENTA DE SPRAY Y DISOLVENTE
		blip = false,
		blipType = 59,
		blipText = 'Pintura y disolvente para yonkis',
		blipColor = 15,
		blipScale = 0.6,
		npc ='a_f_y_skater_01',                                              
		uiText = 'Susi',                                                        
		dialog = 'Pintura y disolvente para yonkis',                                          
		coordinates = vector3(3724.97, 4525.49, 21.47),
		heading = 173.79,                                       
		options = {                                                            
			{'<i class="fa-solid fa-building-memo"></i>Interactuar', 'opensellMenu:ilegalesspray', 'c'},
		},
	},

	{ -- VENTA DE LLAVES PARA LABORATORIO DE DROGA PUBLICA (SETAS)
		npc ='a_m_m_eastsa_01',                                                     
		anim = {                                                            
			animDictionary = 'switch@trevor@dumpster',
			animationName = '002002_01_trvs_14_dumpster_idle', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Amador Rodriguez',                                                        
		dialog = '¿En busca de una llave perdida? por 500 es tuya.',                                                
		coordinates = vector3(-444.69, -784.02, 29.54), 
		heading = 264.21,                                                 
		options = {         
			{'<i class="fa-solid fa-poop"></i>O la tomas o la dejas', 'Quest:LLaves', 'c'},
		},
	},

	{ -- VENTA DE LLAVES PARA LABORATORIO DE DROGA PUBLICA (SETAS)
		npc ='a_m_m_eastsa_01',                                                     
		anim = {                                                            
			animDictionary = 'switch@trevor@dumpster',
			animationName = '002002_01_trvs_14_dumpster_idle', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Fausto Rodriguez',                                                        
		dialog = '¿En busca de una llave perdida? por 500 es tuya.',                                                
		coordinates = vector3(-11.81, -1037.85, 27.92), 
		heading = 330.64,                                                 
		options = {         
			{'<i class="fa-solid fa-poop"></i>O la tomas o la dejas', 'Quest:LLaves', 'c'},
		},
	},

	{ -- ROBO: COMPRA DE LLAVES PARA ALMACEN 
		npc ='a_m_m_eastsa_01',                                                     
		uiText = 'Ramon Garcia',                                                        
		dialog = '¿En busca de una llave perdida? por 500 es tuya.',                                                
		coordinates = vector3(146.03, -3323.66, 5.02), 
		heading = 175.88,                                                 
		options = {         
			{'<i class="fa-solid fa-poop"></i>O la tomas o la dejas', 'Quest:AlmacenRobo', 'c'},
		},
	},

	{ -- VENTA: BOTELLA ROTA
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- autireze = {
		-- 	["gang"] = {"firm", "ottos", "crips", "pirublood", "breakwaters", "families"},
		-- 	["job"] = {},
		-- },          
		npc ='u_m_y_militarybum', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Nate Rose',                                                
		dialog = '¿Que pasa tio? Si me das un poco de droga, te podría dar algo',                                                        
		coordinates = vector3(915.46, -1703.28, 50.26), 
		heading = 359.29,                                                
		options = {                                                            
			{'<i class="fa-solid fa-wine-glass-crack"></i>Interactuar', 'Quest:BottleBreak', 'c'},
		},
	},
	{   -- VENTA: BATE DE BEISBOL
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"firm", "ottos", "crips", "pirublood", "breakwaters", "families"},
		-- 	["job"] = {},
		-- },          
		npc ='a_m_m_soucent_03', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Jose Antonio C',                                                
		dialog = 'Loco, tengo un monton de bates de colección, podría interesarte',                                                        
		coordinates = vector3(1872.95, 3749.51, 31.99), 
		heading = 25.09,                                                
		options = {                                                            
			{'<i class="fa-solid fa-baseball-bat-ball"></i>Interactuar', 'Quest:Bate', 'c'},
		},
	},
	{   -- VENTA: PALANCA
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"ottos", "firm", "ottos", "crips", "pirublood", "breakwaters", "families"},
		-- 	["job"] = {},
		-- },          
		npc ='s_m_m_autoshop_02', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Bob Michigan',                                                
		dialog = '¿Me dejas fumar tio? Ah, que vienes a por herramientas',                                                        
		coordinates = vector3(466.98, -928.88, 27.49), 
		heading = 100.17,                                                
		options = {                                                            
			{'<i class="fa-solid fa-toolbox"></i>Interactuar', 'Quest:Palanca', 'c'},
		},
	},
	{   -- VENTA: PALO DE GOLF
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"firm", "ottos", "pirublood"},
		-- 	["job"] = {},
		-- },          
		npc ='ig_kaylee', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Harir ',                                                
		dialog = 'Hola hermosura, tengo unos palos de golf de mi padre difunto. Quiza os interese',                                                        
		coordinates = vector3(-896.54, -4.93, 42.80),  
		heading = 299.46,                                                
		options = {                                                            
			{'<i class="fa-solid fa-golf-club"></i>Interactuar', 'Quest:PaloGolf', 'c'},
		},
	},
	{   -- VENTA: PALO DE BILLAR
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"firm", "ottos"},
		-- 	["job"] = {},
		-- },          
		npc ='s_m_m_strpreach_01', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Alex Boldween',                                                
		dialog = 'Puedo darte algo que robe de mi trabajo, pero debes mantenerlo en secreto, mi reputación ya esta manchada',                                                        
		coordinates = vector3(-754.33, 5594.90, 40.67),  
		heading = 91.54,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hammer"></i>Interactuar', 'Quest:Martillo', 'c'},
		},
	},
	{  -- VENTA: LLAVE INGLESA
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"firm", "ottos"},
		-- 	["job"] = {},
		-- },          
		npc ='u_f_o_prolhost_01', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Lisa Freeman',                                                
		dialog = 'Me dedico a reparar las aspas del parque eólico',                                                        
		coordinates = vector3(1711.76, 3846.54, 33.93),  
		heading = 128.49,                                                
		options = {                                                            
			{'<i class="fa-solid fa-wrench"></i>Interactuar', 'Quest:LlaveInglesa', 'c'},
		},
	},
	{  -- VENTA: PALO DE BILLAR 2
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"firm", "ottos", "crips"},
		-- 	["job"] = {},
		-- },          
		npc ='a_m_o_soucent_01', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Rupert Jr.',                                                
		dialog = 'No tengo visita desde hace mucho tiempo, te puedo dar esto a cambio de algo.',                                                        
		coordinates = vector3(1265.91, 2743.33, 37.44),  
		heading = 327.10,                                                
		options = {                                                            
			{'<i class="fa-solid fa-spoon"></i>Interactuar', 'Quest:PalodeBillar', 'c'},
		},
	},
	{ -- VENTA: NAVAJAS
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"firm", "ottos", "breakwaters", "ottos"},
		-- 	["job"] = {},
		-- },          
		npc ='a_m_y_ktown_02', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Elias Yukinawa',                                                
		dialog = '¿Quieres que te enseñe mi técnica maestra? Puede que en un futuro seas un gran espadachín como yo.',                                                        
		coordinates = vector3(714.78, 4102.08, 34.79),  
		heading =  82.40,                                            
		options = {                                                            
			{'<i class="fa-solid fa-scalpel"></i>Interactuar', 'Quest:Navajas', 'c'},
		},
	},
	{  -- VENTA: MACHETE
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"firm", "ottos", "pirublood", "ottos"},
		-- 	["job"] = {},
		-- },          
		npc ='a_m_y_salton_01', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Bob Jackson',                                                
		dialog = '¿Tú también estás harto de los cerdos, toma esto te ayudará a deshacerte de ellos?',                                                        
		coordinates = vector3(435.97, 6503.21, 27.74),  
		heading = 182.43,                                             
		options = {                                                            
			{'<i class="fa-solid fa-scalpel"></i>Interactuar', 'Quest:Machete', 'c'}, 
		},
	},
	{ -- VENTA: PUNO AMERICANO
		blip = false,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		-- 	autireze = {
		-- 	["gang"] = {"firm", "ottos", "breakwaters"},
		-- 	["job"] = {},
		-- },          
		npc ='u_m_m_griff_01', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Robert Grey',                                                
		dialog = 'Con ésto, América puede volver a estar bien, si sabes como usarlo.',                                                        
		coordinates = vector3(45.89, 3703.57, 38.76),   
		heading = 328.43,                                             
		options = {                                                            
			{'<i class="fa-solid fa-hand-fist"></i>Interactuar', 'Quest:PunoAmericano', 'c'},
		},
	},

	{ -- MEDICO ILEGAL:  Sandy
		npc ='s_m_m_scientist_01',                                                       
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'John Jones',                                                        
		dialog = 'Solo quiero volver a ver a mi familia, hare lo necesario.',                                                
		coordinates =  vector3(1700.74, 3293.92, 47.92),  
		heading = 207.51,                                                 
		options = {         
			{'<i class="fa-solid fa-syringe"></i>Curarse', 'medical:ilegal', 'c'},
		},
	}, 
	{ -- MEDICO ILEGAL: Los Santos
		npc ='s_m_m_scientist_01',                                                       
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Luke Johnson',                                                        
		dialog = 'Solo quiero volver a ver a mi familia, te curare lo que necesites.',                                                
		coordinates =  vector3(840.94, -2308.86, 29.66),                                           
		heading = 73.46,                                                 
		options = {         
			{'<i class="fa-solid fa-syringe"></i>Curarse', 'medical:ilegal', 'c'},
		},
	}, 
	{ -- VENTA DE TERMITA
		blip = flase,
		blipType = 628,
		blipText = 'Termita',
		blipColor = 15,
		blipScale = 0.6,
		gender = "male",
		npc ='cs_floyd',                                            
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Gonza Gonzales',                                                        
		dialog = '¿En busca de termita? Aqui lo tienes',                                          
		coordinates =   vector3(3092.20, -4692.61, 23.26) , 
		heading =    192.91,                                       
		options = {   
			{'<i class="fa-solid fa-shop"></i>Interactuar', 'rDialog:sell:thermite', 'c'}, 
		},
	}, 
}
