/*
    World.lua, en este archivo se definen los NPCs del mundo, accesibles para qualquier jugador.
    Estos NPCs pueden ofrecer diferentes servicios y diálogos a los jugadores.
    El archivo contiene una tabla que define las propiedades y comportamientos de cada NPC del mundo.
*/

return {
	{ --BANCOS
		blip = true,
		blipType = 276,
		blipText = 'Banco',
		blipColor = 15,
		blipScale = 0.75,
		npc ='a_m_o_salton_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Carter Sullivan',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates = vector3(-109.05, 6471.64, 30.63),
		heading = 224.22,  
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	}, 
	{ --BANCOS
		blip = true,
		blipType = 276,
		blipText = 'Banco',
		blipColor = 15,
		blipScale = 0.75,
		npc ='a_f_y_hipster_04',                                                
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Mason Turner',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates = vector3(313.80, -280.51, 53.16),
		heading = 338.69,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},	
	{ --BANCOS
		blip = true,
		blipType = 276,
		blipText = 'Banco',
		blipColor = 15,
		blipScale = 0.75,
		npc ='cs_molly',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Derek Martinez',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates = vector3(-351.34, -51.27, 48.04),
		heading = 339.24,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},
	{ --BANCOS
		blip = false,
		blipType = 276,
		blipText = 'Banco',
		blipColor = 15,
		blipScale = 0.75,
		npc ='cs_solomon',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},

		uiText = 'Wyatt Mitchell',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates = vector3(252.15, 223.18, 105.29),
		heading = 162.63,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},
	{ --BANCOS
		blip = true,
		blipType = 276,
		blipText = 'Banco',
		blipColor = 15,
		blipScale = 0.75,
		npc ='cs_taostranslator',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Owen Cooper',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates =  vector3(247.03, 224.99, 105.29),
		heading = 164.06 ,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},
	{ --BANCOS
		blip = true,
		blipType = 276,
		blipText = 'Banco',
		blipColor = 15,
		blipScale = 0.75,
		npc ='ig_maude',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Emily Johnson',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates = vector3(1174.97, 2708.23, 37.09) ,
		heading = 181.42,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},
	{ --BANCOS
		blip = true,
		blipType = 276,
		blipText = 'Banco',
		blipColor = 15,
		blipScale = 0.75,
		npc ='ig_djtalignazio',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Megan Brown',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates =  vector3(149.40, -1042.20, 28.37),
		heading = 345.12,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},
	{ --BANCOS
		blip = true,
		blipType = 276,
		blipText = 'Banco',
		blipColor = 15,
		blipScale = 0.75,
		npc ='u_f_y_princess',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Jessica Clark',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates =   vector3(-1212.02, -331.96, 36.78),
		heading = 29.82,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},
	{ --BANCOS
		npc ='u_f_o_eileen',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Sarah Anderson',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates =    vector3(-2961.17, 482.99, 14.70) ,
		heading = 89.37,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},
	{ --BANCOS
		npc ='u_f_o_eileen',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Amanda Moore',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates =    vector3(-2961.17, 482.99, 14.70) ,
		heading =   89.37 ,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},
	{ --BANCOS
		npc ='u_f_o_eileen',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Jennifer Smith',                                                        
		dialog = '¿En qué le puedo ayudar?',                                                
		coordinates =    vector3(-2961.17, 482.99, 14.70) ,
		heading =   89.37 ,                                                
		options = {                                                            
			{'<i class="fa-solid fa-money-check-dollar-pen"></i>Ver cuenta del banco', 'banco:OpenBank', 'c'},
		},
	},

    {  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@prop_human_seat_chair@female@arms_folded@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Kyle Nelson',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =   vector3(-686.47, -1102.85, 13.42),
		heading =  215.31 ,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},
		},
	},
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@prop_human_seat_chair@female@arms_folded@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Kyle Nelson',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =   vector3(-31.34, 170.95, 93.6),
		heading =  118.34 ,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},
		},
	},
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		uiText = 'Kyle Nelson',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =   vector3(-51.73, -578.68, 36.33),
		heading =  68.59 ,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},
		},
	},
	{
		npc ='u_m_m_bikehire_01',                                                     
		uiText = 'Kyle Nelson',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =   vector3(-245.33, -992.93, 28.29),
		heading =  245.00 ,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},
		},
	},
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		uiText = 'Kyle Nelson',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =   vector3(-1354.86, -1130.20, 3.11),
		heading =  330.47 ,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},
		},
	},
	{
		npc ='u_m_m_bikehire_01',                                                     
		uiText = 'Kyle Nelson',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =   vector3(-156.73, 6428.75, 30.92),
		heading =  144.49 ,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},
		},
	},
	{  -- ALQUILER DE BICICLETAS
		npc ='s_m_y_ammucity_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Ethan Baker',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =  vector3(-768.96, 5597.18, 32.60) ,
		heading =    165.49,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},
		},
	},  
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@code_human_in_car_idles@van@ps@idle_c',
			animationName = 'idle_g', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Adrian Ward',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =    vector3(300.74, -1652.76, 31.1) ,
		heading =    321.36  ,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},

		},
	},  
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@code_human_wander_idles_cop@female@static',
			animationName = 'static', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Miles Palmer',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates = vector3(-105.88, 6317.30, 30.58),
		heading =  137.18,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},

		},
	},  
	{  -- ALQUILER DE BICICLETAS
		npc ='a_m_o_tramp_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@code_human_wander_idles_cop@female@static',
			animationName = 'static', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Alejandro Buenomartel',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates = vector3(822.84, -2986.27, 5.02),
		heading =  304.58,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},

		},
	}, 
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@prop_human_seat_chair@male@left_elbow_on_knee@idle_b',
			animationName = 'idle_d', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Gabriel Mitchell',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =   vector3(-1152.76, -1513.21, 3.24) ,
		heading =   35.19,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},

		},
	},  
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@idle_a',
			animationName = 'idle_a', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Samuel Bennett',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates = vector3(-523.03, -1224.80, 17.43) ,
		heading =  335.63,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},

		},
	}, 
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@idle_a',
			animationName = 'idle_a', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Isaac Rodriguez',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates = vector3(270.61, -833.53, 28.29),
		heading =  166.92 ,                                                 
		options = {
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},
		},
	}, 
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@idle_a',
			animationName = 'idle_a', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Spencer Taylor',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =  vector3(-455.00, 261.99, 82.02), 
		heading =    175.89,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},

		},
	}, 
	{  -- ALQUILER DE BICICLETAS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@code_human_in_bus_passenger_idles@male@sit@idle_a',
			animationName = 'idle_a', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Russell Foster',                                                        
		dialog = '¿Qué bicicleta te interesa muchacho?',                                                
		coordinates =   vector3(1200.46, 2657.38, 36.39) , 
		heading =      240.89 ,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-bicycle"></i>BMX', 'rental:bmx', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Cruiser', 'rental:cruiser', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Fixter', 'rental:fixter', 'c'},
			{'<i class="fa-solid fa-bicycle"></i>Tribike', 'rental:tribike', 'c'},

		},
	}, 

    {  -- ALQUILER DE BARCOS
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'abigail_mcs_1_concat-0',
			animationName = 'exportcamera-0',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Dominic Lee',                                                        
		dialog = '¿Estás interesado en alquilar un barco?',                                                
		coordinates = vector3(1274.96, -2743.88, 0.0), 
		heading = 144.03,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-ship"></i>Alquilar barco', 'barco:reysel', 'c'},
		},
	}, 
	{  -- ALQUILER DE BARCOS
		blip = true,
		blipType = 404,
		blipText = 'Alquiler de barcos',
		blipColor = 15,
		blipScale = 0.6,
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'abigail_mcs_1_concat-0',
			animationName = 'exportcamera-0',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Andres Lee',                                                        
		dialog = '¿Estás interesado en alquilar un barco?',                                                
		coordinates = vector3(2359.13, -2125.94, 1.15), 
		heading = 97.95,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-ship"></i>Alquilar barco', 'barco:reysel', 'c', '2'},
		},
	}, 
	{  -- ALQUILER DE BARCOS
		blip = true,
		blipType = 404,
		blipText = 'Alquiler de barcos',
		blipColor = 15,
		blipScale = 0.6,
		npc ='u_m_m_bikehire_01',                                                     
		anim = {                                                            
			animDictionary = 'abigail_mcs_1_concat-0',
			animationName = 'exportcamera-0',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Carles Chafer',                                                        
		dialog = '¿Estás interesado en alquilar un barco?',                                                
		coordinates = vector3(510.31, -3135.23, 5.07), 
		heading = 90.81,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-ship"></i>Alquilar barco', 'barco:reysel', 'c', '3'},
		},
	},

    {  -- MEDICO HOSPITAL 1
		npc ='s_m_m_doctor_01',                                                     
		anim = {                                                            
			animDictionary = 'abigail_mcs_1_concat-0',
			animationName = 'exportcamera-0',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Raul Rubia',                                                        
		dialog = 'Buenas, ¿Tienes cita? Espera tu turno por favor',                                                
		coordinates = vector3(-289.81, -438.74, 29.25),
		heading = 2.0,                
		gender = "male",                                             
		options = {                                                            
			{'<i class="fa-solid fa-bed-pulse"></i>Necesito tratamiento', 'Regreso:medico', 'c'},
		},
	}, 
	{ -- MEDICO HOSPITAL 2
		npc ='s_f_y_scrubs_01',                                                     
		anim = {                                                            
			animDictionary = 'abigail_mcs_1_concat-0',
			animationName = 'exportcamera-0',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Katia Moreno',                                                        
		dialog = 'Buenas, ¿Tienes cita? Espera tu turno por favor',                                                
		coordinates = vector3(-278.51, -441.02, 29.25),
		heading = 75.05,    
		gender = "female",                                             
		options = {                                                            
			{'<i class="fa-solid fa-bed-pulse"></i>Necesito tratamiento', 'Regreso:medico', 'c'},
		},
	},

    { -- CONCESIONARIOS
		blip = true,
		blipType = 227,
		blipText = 'Concesionario: Importación',
		blipColor = 15,
		blipScale = 0.75,
		npc ='cs_siemonyetarian',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Pablo Carmona',                                                        
		dialog = 'Bienvenido al concesionario de importación, ¿Qué desea?',                                                
		coordinates =  vector3(812.91, -3147.59, 5.15),
		heading = 323.40,                                                 
		options = {
			{'<i class="fa-solid fa-cars"></i>Ver catálogo de importación', 'jg-dealerships:client:open-showroom', 'c', 'import'},
		},
	}, 
	{ -- CONCESIONARIOS
		blip = true,
		blipType = 227,
		blipText = 'Concesionario: Sur',
		blipColor = 15,
		blipScale = 0.75,
		npc ='cs_siemonyetarian',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Alberto Macaco',                                                        
		dialog = 'Bienvenido al Premium Deluxe Motorsport, ¿Qué desea?',                                                
		coordinates =  vector3(-775.20, -226.66, 36.43),
		heading = 122.36,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-cars"></i>Ver catálogo', 'jg-dealerships:client:open-showroom', 'c', 'pdm'},
		},
	}, 
	{ -- CONCESIONARIOS
		blip = true,
		blipType = 371,
		blipText = 'Concesionario: Barcos',
		blipColor = 15,
		blipScale = 0.75,
		npc ='cs_siemonyetarian',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'César Abellan',                                                        
		dialog = 'Bienvenido a la tienda de barcos, ¿Qué desea?',                                                
		coordinates =  vector3(-815.47, -1346.77, 4.15),
		heading = 51.97,                                                 
		options = {                                                            
			{'<i class="fa-solid fa-sailboat"></i>Ver catálogo', 'jg-dealerships:client:open-showroom', 'c', 'boats'},
		},
	},

    { -- COCHE INICIAL REGALO
		npc ='a_m_m_prolhost_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Victor Ward',                                                        
		dialog = '¿Vienes a por tu nuevo vehículo? Entra y bienvenido',                                                
		coordinates = vector3(1037.38, -2173.18, 30.53),
		heading =	271.60,                                                 
		options = {         
			{'<i class="fa-solid fa-gift"></i>Entrar a por tu regalo', 'cocheregalo:enter', 'c'},
		},
	}, 

    { -- SURF SHOP
		blip = true,
		blipType = 427,
		blipText = 'Tablas de surf',
		blipColor = 15,
		blipScale = 0.75,
		npc ='g_m_y_azteca_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Jesse Simmons',                                                        
		dialog = '¿Te apetece surfear un poco?',                                                
		coordinates = vector3(-1372.35, -1624.95, 2.73),
		heading =  126.24,                                                 
		options = {
			{'<i class="fa-solid fa-wave"></i>Comprar tabla', 'open:surf:shop', 'c'}
		},
	}, 

    { -- TREVOR CRAFTEO DE GANZUAS
		npc ='player_two',                                                     
		anim = {                                                            
			animDictionary = 'switch@trevor@dumpster',
			animationName = '002002_01_trvs_14_dumpster_idle', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Trevor Philips',                                                        
		dialog = 'Acciones disponibles',                                                
		coordinates = vector3(1964.48, 3807.66, 31.3), 
		heading = 186.58,                                                 
		options = {         
			{'<i class="fa-solid fa-poop"></i>VETE A LA MIERDA', 'Quest:TrevorPhilips', 'c'},
		},
	},

    {    -- CINE
		
		blip = true,
		blipType = 135,
		blipText = 'Cine',
		blipColor = 15,
		blipScale = 0.65,
		npc ='IG_Mason_Duggan',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Noah Foster',                                                
		dialog = 'La entrada cuesta $10',                                                        
		coordinates = vector3(282.54, 199.93, 103.37),
		heading = 288.34,                                                
		options = {                                                            
			{'<i class="fa-solid fa-camera-movie"></i>Comprar entrada', 'cinema:enter', 'c'},
		},
	},
	{    -- CINE
		blip = false,
		blipType = 135,
		blipText = 'Cine',
		blipColor = 15,
		blipScale = 0.65,
		npc ='cs_dale',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Garrett Campbell',                                                
		dialog = 'La entrada cuesta $10',                                                        
		coordinates = vector3(313.98, 188.53, 102.93),
		heading = 25.97,                                                
		options = {                                                            
			{'<i class="fa-solid fa-camera-movie"></i>Comprar entrada', 'cinema:enter', 'c'},
		},
	},
	{    -- CINE
		blip = true,
		blipType = 135,
		blipText = 'Cine',
		blipColor = 15,
		blipScale = 0.65,
		npc ='csb_reporter',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Wesley Parker',                                                
		dialog = 'La entrada cuesta $10',                                                        
		coordinates = vector3(-1422.34, -204.33, 45.50),
		heading = 266.67,                                                
		options = {                                                            
			{'<i class="fa-solid fa-camera-movie"></i>Comprar entrada', 'cinema:enter', 'c'},
		},
	},
	{    -- CINE
		blip = true,
		blipType = 135,
		blipText = 'Cine',
		blipColor = 15,
		blipScale = 0.75,
		npc ='mp_m_g_vagfun_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Derrick Turner',                                                
		dialog = 'La entrada cuesta $10',                                                        
		coordinates = vector3(394.69, -717.93, 28.29),
		heading = 270.05,                                                
		options = {                                                            
			{'<i class="fa-solid fa-camera-movie"></i>Comprar entrada', 'cinema:enter', 'c'},
		},
	},

    { -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Alex Johnson',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                        
		coordinates = vector3(-1834.83, -1233.40, 12.02),
		heading = 39.15,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Tyler Davis',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                          
		coordinates = vector3(2083.06, 3555.30, 41.24),
		heading = 347.82,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Brandon Thompson',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                             
		coordinates = vector3(-1719.86, -1103.81, 12.02),
		heading = 36.90,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Brian Nelson',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                             
		coordinates = vector3(-1693.17, -1099.67, 12.15), 
		heading = 137.74,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Jason Murphy',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                              
		coordinates = vector3(-1646.41, -1086.42, 12.13), 
		heading = 49.79,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Gavin Mitchell',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                               
		coordinates = vector3(-1771.77, -1160.22, 12.02),
		heading = 49.99,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Logan Taylor',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                              
		coordinates = vector3(-1624.44, -1065.55, 12.09), 
		heading = 230.28,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Dylan Harris',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                               
		coordinates = vector3(-1516.05, -952.08, 8.29), 
		heading = 323.06,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Jordan Carter',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                              
		coordinates = vector3(240.32, 166.96, 104.07), 
		heading = 171.62,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES		
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Mason Miller',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                             
		coordinates = vector3(1968.89, 3261.26, 44.87), 
		heading = 318.94,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},
	{ -- HOT DOGS VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hot Dogs',
		blipColor = 47,
		blipScale = 0.4,
		npc ='s_m_m_linecook',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Jason Murphy',                                                
		dialog = '¿Quieres un buen hot dog? Así te quitas el apetito',                                                              
		coordinates = vector3(-1226.55, -1506.50, 3.29), 
		heading = 307.20,                                                
		options = {                                                            
			{'<i class="fa-solid fa-hotdog"></i>Comprar hot-dog', 'Quest:HotDogs', 'c'},
		},
	},

    {   -- BURGER VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hamburguesas',
		blipColor = 25,
		blipScale = 0.4,
		npc ='s_m_m_strvend_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Jackson Fisher',                                                
		dialog = '¿Tienes hambre? Ven que te preparo algo',                                                        
		coordinates = vector3(-1856.65, -1224.38, 12.02),
		heading = 320.02,                                                
		options = {                                                            
			{'<i class="fa-solid fa-burger-lettuce"></i>Comprar hamburguesa', 'Quest:Burger', 'c'},
		},
	},
	{   -- BURGER VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hamburguesas',
		blipColor = 25,
		blipScale = 0.4,
		npc ='s_m_m_strvend_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Carter Martinez',                                                
		dialog = '¿Tienes hambre? Ven que te preparo algo',                                                        
		coordinates = vector3(-1784.72, -1175.81, 12.02), 
		heading = 53.53,                                                
		options = {                                                            
			{'<i class="fa-solid fa-burger-lettuce"></i>Comprar hamburguesa', 'Quest:Burger', 'c'},
		},
	},
	{   -- BURGER VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hamburguesas',
		blipColor = 25,
		blipScale = 0.4,
		npc ='s_m_m_strvend_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Liam Miller',                                                
		dialog = '¿Tienes hambre? Ven que te preparo algo',                                                        
		coordinates = vector3(-1693.77, -1072.81, 12.02), 
		heading = 51.64,                                                
		options = {                                                            
			{'<i class="fa-solid fa-burger-lettuce"></i>Comprar hamburguesa', 'Quest:Burger', 'c'},
		},
	},
	{   -- BURGER VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hamburguesas',
		blipColor = 25,
		blipScale = 0.4,
		npc ='s_m_m_strvend_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Lucas Hall',                                                
		dialog = '¿Tienes hambre? Ven que te preparo algo',                                                        
		coordinates = vector3(-1692.94, -1112.82, 12.16), 
		heading = 324.45,                                                
		options = {                                                            
			{'<i class="fa-solid fa-burger-lettuce"></i>Comprar hamburguesa', 'Quest:Burger', 'c'},
		},
	},
	{   -- BURGER VENDEDORES
		blip = true,
		blipType = 628,
		blipText = 'Hamburguesas',
		blipColor = 25,
		blipScale = 0.4,
		npc ='s_m_m_strvend_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Caleb Harris',                                                
		dialog = '¿Tienes hambre? Ven que te preparo algo',                                                        
		coordinates = vector3(-1616.54, -1042.53, 12.17), 
		heading = 145.78,                                                
		options = {                                                            
			{'<i class="fa-solid fa-burger-lettuce"></i>Comprar hamburguesa', 'Quest:Burger', 'c'},
		},
	},

    { -- PARACAIDAS		
		blip = true,
		blipType = 550,
		blipText = 'Paracaidismo',
		blipColor = 48,
		blipScale = 0.7,
		npc ='a_m_y_runner_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@code_human_cross_road@female@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Aiden Ward',                                                
		dialog = '¿Quieres disfrutar de una nueva aventura?',
		coordinates = vector3(450.07, 5584.99, 780), 
		heading = 276.09,                                                
		options = {                                                            
			{'<i class="fa-solid fa-parachute-box"></i>Saltar en paracaidas', 'slatar:show', 'c'},
			{'<i class="fa-solid fa-parachute-box"></i>Comprar Paracaidas', 'slatar:buy', 'c'}
		},
	},

    { -- CHATARREROS 
		blip = true,
		blipType = 643,
		blipText = 'Chatarrero',
		blipColor = 15,
		blipScale = 0.4,
		npc ='u_m_m_griff_01',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Nathan Hughes',                                                
		dialog = '¿Que tienes para mi colega?',
		coordinates = vector3(2339.31, 3058.32, 47.15), 
		heading = 177.51,                                                
		options = {                                                            
			{'<i class="fa-solid fa-credit-card"></i>Vender chatarra', 'rDialog:sell:materials:Chatarras', 'c'},
		},
	},
	{ -- CHATARREROS; ALUMINIO
		blip = true,
		blipType = 643,
		blipText = 'Chatarrero',
		blipColor = 15,
		blipScale = 0.4,
		npc ='u_m_m_filmdirector',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Austin Bennett',                                                
		dialog = '¿Que tienes para mi colega?',
		coordinates = vector3(1265.78, -1907.35, 37.51), 
		heading = 1.76,                                                
		options = {                                                            
			{'<i class="fa-solid fa-credit-card"></i>Vender aluminio', 'rDialog:sell:materials:Aluminio', 'c'},
		},
	},
	{ -- CHATARREROS; VIDRIO
		blip = true,
		blipType = 643,
		blipText = 'Chatarrero',
		blipColor = 15,
		blipScale = 0.4,
		npc ='s_m_m_janitor',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base',  
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 0,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Jonathan Carter',                                                
		dialog = '¿Que tienes para mi colega?',
		coordinates = vector3(1074.38, -2450.76, 28.13), 
		heading = 92.05,                                                
		options = {                                                            
			{'<i class="fa-solid fa-credit-card"></i>Vender vidrio', 'rDialog:sell:materials:Vidrio', 'c'},
		},
	},

    { -- TIENDA DE ELECTRONICA
		blip = true,
		blipType = 521,
		blipText = 'Tienda de electrónica',
		blipColor = 15,
		blipScale = 0.6,
		npc ='cs_paper',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Miles Palmer',                                                
		dialog = '¡Los últimos moviles de la nueva generación! Compra uno.',                                                        
		coordinates = vector3(-1207.95, -1502.46, 3.37), 
		heading = 128.00,                                                
		options = {                                                            
			{'<i class="fa-solid fa-transformer-bolt"></i>Interactuar', 'opensellMenu:electronica', 'c'},
		},
	},

    { -- TIENDA DE ANIMALES
		blip = true,
		blipType = 442,
		blipText = 'Tienda de Animales',
		blipColor = 15,
		blipScale = 0.6,
		npc ='a_m_y_business_02', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Fredic Bennett',                                                
		dialog = '¿Quieres una compañia para toda la vida?',                                                        
		coordinates = vector3(562.30, 2741.57, 41.87), 
		heading = 183.79,                                                
		options = {                                                            
			{'<i class="fa-solid fa-shield-dog"></i>Interactuar', 'openAnimalShop', 'c'},
		},
	},
    { -- TIENDA DE ANIMALES COMIDA PARA ANIMALES
		npc ='a_m_y_hipster_02',                                                     
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Mike De La Cruz',                                                        
		dialog = '¿Qué tienes para mí?',                                                
		coordinates = vector3(567.88, 2742.01, 41.20),
		heading =  132.46,                                                 
		options = {         
			{'<i class="fa-solid fa-bowl-food"></i>Comida Para Perro (20$)', 'opendialog:tiendaanimal:comidaperro', 'c'},
		},
	},

    {  -- ACTIVIDAD: MOTOS
		blip = false,
		blipType = 442,
		blipText = 'Comprar motos',
		blipColor = 15,
		blipScale = 0.6,
		npc ='cs_jimmyboston', 
		anim = {                                                            
			animDictionary = 'amb@world_human_aa_smoke@male@idle_a',
			animationName = 'idle_c', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},  
		uiText = 'Ernesto Gomez',                                                
		dialog = '¿Quieres subirte a una moto y disfrutar del viento en la cara? Este es tu sitio.',                                                        
		coordinates = vector3(1128.85, 2125.06, 54.54), 
		heading = 263.32,                                                
		options = {                                                            
			{'<i class="fa-solid fa-motorcycle"></i>Interactuar', 'openActivi:Motos', 'c'},
		},
	},

    {  -- VAPER SHOP
		npc ='a_m_m_polynesian_01',      
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Maverick Johnson',                                                        
		dialog = '¿Necesitas algo de mi? ¿Quieres conseguir algo para llenar tus pulmones de humo?',                                                
		coordinates =   vector3(-1196.91, -1520.59, 3.38)  , 
		heading =     210.38 ,                                          
		options = {   
			{'<i class="fa-solid fa-cannabis"></i>Interactuar', 'opensellMenu:vapershop', 'c'}, 
		},
	},

    { -- BADULAQUE FRENTE AL GALAXY
		blip = true,
		blipType = 628,
		blipText = 'Badulaque',
		blipColor = 15,
		blipScale = 0.6,
		npc ='s_m_m_migrant_01',                                            
		anim = {                                                            
			animDictionary = 'amb@world_human_golf_player@male@base',
			animationName = 'base', 
			blendInSpeed = 8.0,
			blendOutSpeed = 0.0,
			duration = -1,
			flag = 1,
			playbackRate = 0,
			lockX = 0,
			lockY = 0,
			lockZ = 0,
		},
		uiText = 'Manuel Rodriguez',                                                        
		dialog = '¿Necesitas algo de mi? Tengo los mejores precios de la ciudad',                                          
		coordinates =   vector3(378.02, 326.32, 102.57) , 
		heading =    160.22,                                       
		options = {   
			{'<i class="fa-solid fa-shop"></i>Interactuar', 'opensellMenu:productosbadu', 'c'}, 
		},
	},
}